title: Protocol404 Blog
description: Catatan, tutorial, dan komunitas
url: "https://protocol404.github.io"   # ganti dengan username-mu
baseurl: ""

permalink: /:title/

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
